package com.luis.model;

// Generated 25-abr-2014 21:04:13 by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.Set;

/**
 * Conocimientos generated by hbm2java
 */
public class Conocimientos implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	private Integer idconocimientos;
	private String nombre;
	private Set<Empleado> empleados = new HashSet<Empleado>(0);

	public Conocimientos() {
	}

	public Conocimientos(String nombre) {
		this.nombre = nombre;
	}

	public Conocimientos(String nombre, Set<Empleado> empleados) {
		this.nombre = nombre;
		this.empleados = empleados;
	}

	public Integer getIdconocimientos() {
		return this.idconocimientos;
	}

	public void setIdconocimientos(Integer idconocimientos) {
		this.idconocimientos = idconocimientos;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set<Empleado> getEmpleados() {
		return this.empleados;
	}

	public void setEmpleados(Set<Empleado> empleados) {
		this.empleados = empleados;
	}

}
